channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=26.0.1
- pip:
  - mlflow==3.0.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==7.0.0
  - scikit-learn==1.3.0
  - scipy==1.15.3
name: mlflow-env
